// <auto-generated />
using System;
using HourControl.Infra.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HourControl.Infra.Data.Migrations
{
    [DbContext(typeof(SimpleApiDbContext))]
    [Migration("20220802160405_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0-preview.6.22329.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HourControl.Domain.Entitys.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("timestamp");

                    b.Property<DateTime?>("DeletedIn")
                        .HasColumnType("timestamp");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RegisteredIn")
                        .HasColumnType("timestamp");

                    b.Property<TimeSpan?>("TimeEnd")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("TimeStart")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("TimeTotal")
                        .HasColumnType("time");

                    b.Property<DateTime>("UpdatedIn")
                        .HasColumnType("timestamp");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Activity", (string)null);
                });

            modelBuilder.Entity("HourControl.Domain.Entitys.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("varchar");

                    b.Property<DateTime?>("DeletedIn")
                        .HasColumnType("timestamp");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar");

                    b.Property<DateTime>("RegisteredIn")
                        .HasColumnType("timestamp");

                    b.Property<DateTime>("UpdatedIn")
                        .HasColumnType("timestamp");

                    b.HasKey("Id");

                    b.ToTable("Project", (string)null);
                });

            modelBuilder.Entity("HourControl.Domain.Entitys.Activity", b =>
                {
                    b.HasOne("HourControl.Domain.Entitys.Project", "Project")
                        .WithMany("Activitys")
                        .HasForeignKey("ProjectId");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("HourControl.Domain.Entitys.Project", b =>
                {
                    b.Navigation("Activitys");
                });
#pragma warning restore 612, 618
        }
    }
}
